name: CI
on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./packages/frontend
        run: npm i
      - name: Build
        working-directory: ./packages/frontend
        run: npm run build
      - name: Deploy
        working-directory: ./packages/frontend
        run: cp -r dist/* /apps/test
